language: java
jdk:
  - openjdk8

branches:
  only:
    - master
    - develop
#    - /^feature\/.*$/

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
    slack: woowahan-techcamp:DUmMgWkADZU9aC7hhTK2HPZc

after_success:
- ./gradlew jacocoTestReport coveralls

before_deploy:
- zip -r recipehub-develop *
- mkdir -p deploy
- mv recipehub-develop.zip deploy/recipehub-develop.zip

deploy:
- provider: s3
  local_dir: deploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: recipehub-deploy
  region: ap-northeast-2
  skip_cleanup: true
  acl: public_read
  wait-until-deployed: true
  on:
    repo: wwh-techcamp-2018/team5-fiveMasterGuys
    branch: develop

- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: recipehub-deploy
  key: recipehub-develop.zip
  bundle_type: zip
  application: recipehub
  deployment_group: recipehub-deploy-group
  region: ap-northeast-2
  wait-until-deployed: true
  on:
    repo: wwh-techcamp-2018/team5-fiveMasterGuys
    branch: develop